# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arfoUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ARFOUi(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2250, 1450)
        MainWindow.setStyleSheet("alternate-background-color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("alternate-background-color: rgb(0, 0, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border-top-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.ARFOUi = QtWidgets.QLabel(self.centralwidget)
        self.ARFOUi.setGeometry(QtCore.QRect(-30, -1, 2300, 1491))
        self.ARFOUi.setText("")
        self.ARFOUi.setPixmap(QtGui.QPixmap("../../Pictures/black.jpg"))
        self.ARFOUi.setScaledContents(True)
        self.ARFOUi.setObjectName("ARFOUi")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(2020, 470, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(2105, 470, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.arfoUI = QtWidgets.QTextBrowser(self.centralwidget)
        self.arfoUI.setGeometry(QtCore.QRect(70, 50, 501, 101))
        font = QtGui.QFont()
        font.setFamily("游明朝")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.arfoUI.setFont(font)
        self.arfoUI.setStyleSheet("background:transparent;\n"
"font: 28pt \"游明朝\";\n"
"border:none;\n"
"color: rgb(255, 255, 255);")
        self.arfoUI.setObjectName("arfoUI")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(70, 200, 501, 101))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border-radius:none;\n"
"font: 28pt \"游明朝\";\n"
"")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(710, 300, 791, 600))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Pictures/arfocore.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(1610, 30, 551, 381))
        self.calendarWidget.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 18pt \"UD デジタル 教科書体 NK-B\";\n"
"background-color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(0, 0, 0);")
        self.calendarWidget.setObjectName("calendarWidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(70, 351, 501, 120))
        self.textEdit.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:none;\n"
"font: 63 25pt \'游明朝 Demibold\';\n"
"color:white;")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(310, 482, 200, 225))
        self.textEdit_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:none;\n"
"font: 63 72pt \'游明朝 Demibold\';\n"
"color: rgb(85, 255, 255);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(140, 730, 381, 101))
        self.textEdit_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:none;\n"
"font: 63 33pt \'游明朝 Demibold\';\n"
"color:white;")
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(570, 840, 1071, 661))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Pictures/voice.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(970, 80, 500, 171))
        self.textEdit_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"background:transparent;\n"
"font: 63 40pt \\\'游明朝 Demibold\\\';\n"
"border-radius:none;")
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 470, 231, 251))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../Pictures/weatherimage.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(1720, 680, 451, 491))
        self.textEdit_5.setStyleSheet("color:white;\n"
"background:transparent;\n"
"")
        self.textEdit_5.setObjectName("textEdit_5")
        self.ARFOUi.raise_()
        self.label.raise_()
        self.pushButton_2.raise_()
        self.arfoUI.raise_()
        self.textBrowser_2.raise_()
        self.calendarWidget.raise_()
        self.textEdit.raise_()
        self.textEdit_2.raise_()
        self.textEdit_3.raise_()
        self.textEdit_4.raise_()
        self.pushButton.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.textEdit_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Run"))
        self.pushButton_2.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_ARFOUi()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
